openapi: "3.0.2"
info:
  title: You-Never-Be-Alone User API
  version: "1.0.0-SNAPSHOT"

paths:
  /users:
    put:
      operationId: putUser
      summary: Updates or Creates a User
      responses:
        '200':
          description: User successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    get:
      operationId: getUsers
      summary: Returns a list of all Users
      responses:
        '200':
          description: a list of Users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /auth/login:
    post:
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: 'Successful login'
          content:
            application/json:
              schema:
                description: 'the tokens'
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
  /auth/register:
    post:
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: 'registration successful'
          content:
            application/json:
              schema:
                description: 'successful registration response'
                type: object
                properties:
                  id:
                    type: string
                    format: UUID

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstname:
          type: string
        lastname:
          type: string
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
