name: Ride API CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: verify
        run: mvn --batch-mode --update-snapshots verify
      - name: debug
        run: |
          echo "token is ${{ secrets.DEPLOY_TOKEN }}";
          echo "token is ${DEPLOY_TOKEN}";
      - name: deploy
        if: github.ref == 'refs/heads/main'    
        run: mvn --batch-mode -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        
